INSERT INTO Savants (id_savant, type_savant, nom, prenom) VALUES
('1', 'A','Abel', 'Niels Henrik'),
('2', 'A','Accum', 'Friedrich Christian'),
('3', 'A','Achard', 'Franz Karl'),
('4', 'A','Acharius', 'Erik'),
('5', 'A','Adanson', 'Michel'),
('6', 'A','Addison', 'Thomas'),
('7', 'A','Adet', 'Pierre-Auguste'),
('8', 'A','Adrain', 'Robert'),
('9', 'A','Aepinus', 'Franz Ulrich Theodosius'),
('10', 'A','Agardh', 'Carl Adolph'),
('11', 'A','Agnesi', 'Maria Gaetana'),
('12', 'A','Aida', 'Yasuaki [Ammei]'),
('13', 'A','Airy', 'George Biddell'),
('14', 'A','Aiton', 'William'),
('15', 'A','Aiton', 'William Townsend'),
('16', 'A','Ajima', 'Nanobu (Chokuyen)'),
('17', 'A','Alberti', 'Friedrich August von'),
('18', 'A','Albinus', 'Bernard'),
('19', 'A','Albinus', 'Bernard Siegfried'),
('20', 'A','Albinus', 'Christiaan Bernard'),
('21', 'A','Albinus', 'Frederik Bernard'),
('22', 'A','Aldini', 'Giovanni'),
('23', 'A','Alembert', 'Jean le Rond d\''),
('24', 'A','Alzate y Ramirez', 'José Antonio'),
('25', 'A','Amici', 'Giovanni Battista'),
('26', 'A','Amontons', 'Guillaume'),
('27', 'A','Ampère', 'André Marie'),
('28', 'A','Anville', 'Jean-Baptiste Bourguignon d\''),
('29', 'A','Arago', 'Dominique François Jean'),
('30', 'A','Arbogast', 'Louis François Antoine'),
('31', 'A','Arbuthnot', 'John'),
('32', 'A','Archiac', 'Etienne Jules Ad. de Saint-Simon, vicomte d\''),
('33', 'A','Arduino', 'Giovanni'),
('34', 'A','Arfvedson', 'Johann August'),
('35', 'A','Argand', 'Jean Robert'),
('36', 'A','Argelander', 'Friedrich Wilhelm August'),
('37', 'A','Argenville', 'Antoine-Joseph Dezallier d\''),
('38', 'A','Artedi', 'Peter'),
('39', 'A','Asada (Ayabe)', 'Gôryû (Yasuaki)'),
('40', 'A','Assalti', 'Pietro'),
('41', 'A','Astruc', 'Jean'),
('42', 'A','Atwood', 'George'),
('43', 'A','Aubuisson de Voisins', 'Jean-François d\''),
('44', 'A','Audouin', 'Jean Victor'),
('45', 'A','Audubon', 'Jean Jacques (John James)'),
('46', 'A','Auenbrugger', 'Joseph Leopold'),
('47', 'A','Avogadro', 'Amedeo'),
('48', 'A','Azara', 'Félix de'),
('49', 'A','Babbage', 'Charles'),
('50', 'A','Babinet', 'Jacques'),
('51', 'A','Babington', 'William'),
('52', 'A','Bachmann (Rivinus)', 'Augustus Quirinus'),
('53', 'A','Baer', 'Karl Ernst von'),
('54', 'A','Baglivi (Armeno)', 'Georgius'),
('55', 'A','Baier', 'Johann Jacob'),
('56', 'A','Baillie', 'Matthew'),
('57', 'A','Bailly', 'Jean-Sylvain'),
('58', 'A','Baily', 'Francis'),
('59', 'A','Baker', 'Henry'),
('60', 'A','Bakewell', 'Robert'),
('61', 'A','Balard', 'Antoine Jérôme'),
('63', 'A','Barchusen', 'Johann Conrad'),
('64', 'A','Barclay', 'John'),
('65', 'A','Barlow', 'Peter'),
('66', 'A','Barrande', 'Joachim'),
('67', 'A','Barry', 'Martin'),
('68', 'A','Barthez', 'Paul-Joseph'),
('69', 'A','Barton', 'Benjamin Smith'),
('70', 'A','Bartram', 'John'),
('71', 'A','Bartram', 'William'),
('72', 'A','Bassi', 'Agostino Maria'),
('73', 'A','Bauer', 'Ferdinand Lucas'),
('74', 'A','Bauer', 'Franz Andreas'),
('75', 'A','Baumé', 'Antoine'),
('76', 'A','Bayen', 'Pierre'),
('77', 'A','Bayes', 'Thomas'),
('78', 'A','Beaumont', 'William'),
('79', 'A','Beccaria', 'Giambattista'),
('80', 'A','Beckmann', 'Johann'),
('81', 'A','Becquerel', 'Antoine-César'),
('82', 'A','Beddoes', 'Thomas'),
('83', 'A','Beer', 'Wilhelm'),
('84', 'A','Bélidor', 'Bernard Forest de'),
('85', 'A','Bell', 'Charles'),
('86', 'A','Bellani', 'Angelo'),
('87', 'A','Bellavitis', 'Giusto'),
('88', 'A','Bellini', 'Lorenzo'),
('89', 'A','Bellinsgauzen (Bellinghausen)', 'Faddei F.'),
('90', 'A','Bentham', 'George'),
('91', 'A','Benzenberg', 'Johann Friedrich'),
('92', 'A','Bérard', 'Jacques Etienne'),
('93', 'A','Bérard', 'Frédéric (Joseph)'),
('94', 'A','Berger', 'Johann Gottfried'),
('95', 'A','Bergman', 'Torbern Olof'),
('96', 'A','Bering', 'Vitus'),
('97', 'A','Beringer', 'Johann Bartholomaeus Adam'),
('98', 'A','Berkeley', 'George'),
('99', 'A','Berkeley', 'Miles Joseph'),
('100', 'A','Bernoulli', 'Daniel (I)'),
('101', 'A','Bernoulli', 'Jakob I'),
('102', 'A','Bernoulli', 'Jakob II'),
('103', 'A','Bernoulli', 'Johann (Jean) I'),
('104', 'A','Bernoulli', 'Johann (Jean) II'),
('106', 'A','Bernoulli', 'Nikolaus I'),
('107', 'A','Bernoulli', 'Nikolaus II'),
('108', 'A','Berthier', 'Pierre'),
('109', 'A','Berthold', 'Arnold Adolphe'),
('110', 'A','Berthollet', 'Claude Louis, comte'),
('111', 'A','Bertholon de Saint-Lazare', 'Pierre'),
('112', 'A','Berzelius', 'Jöns Jacob'),
('113', 'A','Bessel', 'Friedrich Wilhelm'),
('114', 'A','Betancourt y Molina', 'Augustin de'),
('115', 'A','Beudant', 'François-Sulpice'),
('116', 'A','Bexon', 'Gabriel Léopold Charles Amé'),
('117', 'A','Bezout', 'Etienne'),
('118', 'A','Bichat', 'Marie-François-Xavier'),
('119', 'A','Bidloo', 'Govard'),
('120', 'A','Biela', 'Wilhelm von'),
('121', 'A','Bienaymé', 'Irénée-Jules'),
('122', 'A','Bion', 'Nicolas'),
('123', 'A','Biot', 'Jean-Baptiste'),
('124', 'A','Bird', 'John'),
('125', 'A','Birt', 'William Radcliff'),
('126', 'A','Bischof', 'Carl Gustav Christoph'),
('127', 'A','Bischoff', 'Gottlieb Wilhelm'),
('128', 'A','Black', 'James'),
('129', 'A','Black', 'Joseph'),
('130', 'A','Blagden', 'Charles'),
('131', 'A','Blainville', 'Henri Marie Ducotray de'),
('132', 'A','Blair', 'Patrick'),
('133', 'A','Blumenbach', 'Johann Friedrich'),
('134', 'A','Bobillier', 'Etienne'),
('135', 'A','Bochart de Saron', 'Jean-Baptiste-Gaspard'),
('136', 'A','Bode', 'Johann Elert'),
('137', 'A','Boerhaave', 'Hermann'),
('138', 'A','Boguslavsky (Boguslawski)', 'Palm Heinrich Ludwig von'),
('139', 'A','Bohn (Bohne)', 'Johannes'),
('140', 'A','Bolotov', 'Andrei Timofeevitch'),
('141', 'A','Bolyai', 'Farkas (Wolfgang)'),
('142', 'A','Bolyai', 'Janos (Johann)'),
('143', 'A','Bolzano', 'Bernard'),
('144', 'A','Bonaparte', 'Charles Lucien'),
('145', 'A','Bond', 'William Cranch'),
('146', 'A','Bonnet', 'Charles'),
('147', 'A','Bonvicino (Buonvicino; Bonvoisin)', 'Costanzo Benedetto'),
('148', 'A','Borda', 'Jean-Charles'),
('149', 'A','Bordeu', 'Théophile de'),
('150', 'A','Born', 'Ignaz Edler von'),
('151', 'A','Bory de Saint-Vincent', 'Jean Bapitste Georges Marie, baron'),
('152', 'A','Bosc d\'Antic', 'Louis Augustin Guillaume'),
('153', 'A','Bose', 'Georg Matthias'),
('154', 'A','Boskovic (Boscovich)', 'Rudjer Josip (Ruggiero Giuseppe)'),
('155', 'A','Bossut', 'Charles'),
('156', 'A','Bostock', 'John'),
('157', 'A','Boucher de Crèvecoeur de Perthes', 'Jacques'),
('158', 'A','Boué', 'Ami (Amédée)'),
('159', 'A','Bougainville', 'Louis-Antoine, comte de'),
('160', 'A','Bouguer', 'Pierre'),
('161', 'A','Boullanger', 'Nicolas-Antoine'),
('162', 'A','Bourguet', 'Louis'),
('163', 'A','Bournon', 'Jacques-Louis, comte de'),
('164', 'A','Boussingault', 'Jean Baptiste Joseph Dieudonné'),
('165', 'A','Bouvard', 'Alexis'),
('166', 'A','Bowditch', 'Nathaniel'),
('167', 'A','Braconnot', 'Henri'),
('168', 'A','Bradley', 'James'),
('169', 'A','Bradley', 'Richard'),
('170', 'A','Braikenridge (Brakenridge)', 'William'),
('171', 'A','Brande', 'William Thomas'),
('172', 'A','Brandes', 'Heinrich Wilhelm'),
('173', 'A','Brandt', 'Georg'),
('174', 'A','Brandt', 'Johann Friedrich (Fedor Fedorovic)'),
('175', 'A','Brashman (Braschmann)', 'Nikolai Dmitrievich (Nicolaus)'),
('176', 'A','Braun', 'Alexander Carl Heinrich'),
('177', 'A','Breguet', 'Louis François Clément'),
('178', 'A','Breislak', 'Scipione'),
('179', 'A','Breithaupt', 'Johann Friedrich August'),
('180', 'A','Bremiker', 'Carl'),
('181', 'A','Breschet', 'Gilbert'),
('182', 'A','Bret', 'Jean Jacques'),
('183', 'A','Bretonneau', 'Pierre F.'),
('184', 'A','Brewster', 'David'),
('185', 'A','Brianchon', 'Charles-Julien'),
('186', 'A','Bright', 'Richard'),
('187', 'A','Bring', 'Erland Samuel'),
('188', 'A','Brinkley', 'John'),
('189', 'A','Brisbane', 'Thomas Makdougall'),
('190', 'A','Brisson', 'Barnabé'),
('191', 'A','Brisson', 'Mathurin-Jacques'),
('192', 'A','Brocchi', 'Giovanni Battista'),
('193', 'A','Brochant de Villiers', 'André Jean François Marie'),
('194', 'A','Brodie', 'Benjamin Collins Sr'),
('195', 'A','Bromell (Bromelius)', 'Magnus von'),
('196', 'A','Brongniart', 'Adolphe-Théodore'),
('197', 'A','Brongniart', 'Alexandre'),
('198', 'A','Bronn', 'Heinrich Georg'),
('199', 'A','Broussais', 'François Joseph Victor'),
('200', 'A','Broussonet', 'Pierre-Auguste-Marie'),
('201', 'A','Brown', 'Robert'),
('202', 'A','Brownrigg', 'William'),
('203', 'A','Bruce', 'James'),
('204', 'A','Buache', 'Philippe'),
('205', 'A','Buch', '[Christian] Leopold von'),
('206', 'A','Bucholz', 'Christian Friedrich'),
('207', 'A','Buckland', 'William'),
('208', 'A','Bucquet', 'Jean-Baptiste-Michel'),
('209', 'A','Budan de Boislaurent', 'Ferdinand François Désiré'),
('210', 'A','Buffon', 'Georges-Louis Leclerc, comte de'),
('211', 'A','Bunyakovsky', 'Viktor Yakovlevich'),
('212', 'A','Buonanni', 'Filippo'),
('213', 'A','Burdach', 'Karl Friedrich'),
('214', 'A','Bürg', 'Johann Tobias'),
('215', 'A','Burnet', 'Thomas'),
('216', 'A','Busch', 'August Ludwig'),
('217', 'A','Cabanis', 'Pierre-Jean-Georges'),
('219', 'A','Cadet de Gassicourt', 'Louis-Claude'),
('218', 'A','Cadet de Gassicourt', 'Charles-Louis'),
('220', 'A','Cadet de Vaux', 'Antoine-Alexis-François'),
('221', 'A','Cagniard de la Tour', 'Charles'),
('222', 'A','Calandrelli', 'Giuseppe'),
('223', 'A','Calandrelli', 'Ignazio'),
('224', 'A','Caldani', 'Leopoldo Marcantonio'),
('225', 'A','Caldas', 'Francisco José de'),
('226', 'A','Callan', 'Nicholas'),
('228', 'A','Campani', 'Giuseppe'),
('229', 'A','Camper', 'Peter (Petrus)'),
('230', 'A','Camus', 'Charles-Etienne-Louis'),
('231', 'A','Cancrin (Cancrinus)', 'Franz Ludwig von'),
('232', 'A','Candolle', 'Augustin-Pyramus de'),
('233', 'A','Canton', 'John'),
('234', 'A','Carangeot', 'Arnould'),
('235', 'A','Carlisle', 'Anthony'),
('236', 'A','Carnall', 'Rudolf von'),
('237', 'A','Carnot', 'Lazare-Nicolas-Marguerite'),
('238', 'A','Carnot', 'Nicolas Léonard Sadi'),
('239', 'A','Casal Julian', 'Gaspar Roque Francisco Narciso'),
('241', 'A','Cassini I', 'Gian Domenico (Jean-Dominique )'),
('242', 'A','Cassini II', 'Jacques'),
('243', 'A','Cassini IV', 'Jean-Dominique'),
('240', 'A','Cassini de Thury (Cassini III)', 'César-François'),
('244', 'A','Castel', 'Louis-Bertrand'),
('245', 'A','Castillon (Castiglione)', 'Johann (Giovanni Francesco Melchiore Salvemini)'),
('246', 'A','Catesby', 'Mark'),
('247', 'A','Cauchy', 'Augustin-Louis'),
('248', 'A','Cavallo', 'Tiberius'),
('249', 'A','Cavanilles', 'Antonio José'),
('250', 'A','Cavendish', 'Henry'),
('251', 'A','Caventou', 'Joseph-Bienaimé'),
('252', 'A','Cels', 'Jacques-Philippe-Martin'),
('253', 'A','Celsius', 'Anders'),
('254', 'A','Cervantes', 'Vicente'),
('255', 'A','Cestoni', 'Giacinto'),
('256', 'A','Ceva', 'Giovanni'),
('257', 'A','Ceva', 'Tommaso'),
('258', 'A','Challis', 'James'),
('259', 'A','Chambers', 'Robert'),
('260', 'A','Chamisso', 'Adelbert von'),
('261', 'A','Chappe d\'Auteroche', 'Jean-Baptiste'),
('262', 'A','Chaptal', 'Jean-Antoine'),
('263', 'A','Chardenon', 'Jean Pierre'),
('264', 'A','Charles', 'Jacques-Alexandre-César'),
('265', 'A','Charleton', 'Walter'),
('266', 'A','Charpentier', 'Johann (Jean) de'),
('267', 'A','Chasles', 'Michel'),
('268', 'A','Châtelet', 'Gabrielle-Emilie Le Tonnelier de Breteuil, marquise du'),
('269', 'A','Chenevix', 'Richard'),
('270', 'A','Chevallier', 'Jean-Baptiste-Alphonse'),
('271', 'A','Chevallier', 'Temple'),
('272', 'A','Chevreul', 'Michel Eugène'),
('273', 'A','Cheyne', 'George'),
('274', 'A','Chladni', 'Ernst Friedrich Florenz'),
('275', 'A','Christie', 'Samuel Hunter'),
('276', 'A','Christol', 'Jules de'),
('277', 'A','Clairaut', 'Alexis-Claude'),
('278', 'A','Clapeyron', 'Benoît-Pierre-Emile'),
('279', 'A','Clark', 'Alvan'),
('280', 'A','Clark', 'Thomas'),
('281', 'A','Clarke', 'Edward Daniel'),
('282', 'A','Clarke', 'Samuel'),
('283', 'A','Clarke', 'William Branwhite'),
('284', 'A','Claus (Klaus)', 'Carl Ernst (Karl Karlovich)'),
('285', 'A','Clausen', 'Thomas'),
('286', 'A','Cleaveland', 'Parker'),
('287', 'A','Clément', 'Nicolas'),
('288', 'A','Clerck', 'Carl Alexander'),
('289', 'A','Clift', 'William'),
('290', 'A','Clouet', 'Jean-François'),
('291', 'A','Cogrossi', 'Carlo Francesco'),
('292', 'A','Colden', 'Cadwallader'),
('293', 'A','Collet-Descotils', 'Hippolyte-Victor'),
('294', 'A','Collinson', 'Peter'),
('295', 'A','Combes', 'Charles-Pierre-Mathieu'),
('296', 'A','Commerson', 'Philibert'),
('297', 'A','Comte', 'Isidore Auguste Marie François'),
('298', 'A','Condillac', 'Etienne Bonnot, abbé de'),
('299', 'A','Condorcet', 'Marie-Jean-Antoine-Nicolas Caritat, marquis de'),
('300', 'A','Congreve', 'William'),
('301', 'A','Conrad', 'Timothy Abbott'),
('302', 'A','Conybeare', 'William Daniel'),
('303', 'A','Cook', 'James'),
('304', 'A','Cooper', 'Thomas'),
('305', 'A','Cordier', 'Pierre-Louis-Antoine'),
('306', 'A','Coriolis', 'Gaspard Gustave de'),
('307', 'A','Cornette', 'Claude-Melchior'),
('308', 'A','Coronelli', 'Vincenzo Maria'),
('309', 'A','Corti', 'Bonaventura'),
('310', 'A','Corvisart', 'Jean-Nicolas'),
('311', 'A','Cotes', 'Roger'),
('312', 'A','Cotte', 'Louis'),
('313', 'A','Cotugno', 'Domenico Felice Antonio'),
('314', 'A','Coulomb', 'Charles Augustin'),
('315', 'A','Cournot', 'Antoine-Augustin'),
('316', 'A','Courtivron', 'Gaspard le Compasseur de Créquy-Montfort, marquis de'),
('317', 'A','Courtois', 'Bernard'),
('318', 'A','Craig', 'John'),
('319', 'A','Cramer', 'Gabriel'),
('320', 'A','Cramer', 'Johann Andreas'),
('321', 'A','Crawford', 'Adair'),
('322', 'A','Crell', 'Lorenz Florenz Friedrich von'),
('323', 'A','Crelle', 'August Leopold'),
('324', 'A','Cronstedt', 'Axel Fredrik'),
('325', 'A','Crousaz', 'Jean-Pierre de'),
('326', 'A','Cruickshank', 'William Cumberland'),
('327', 'A','Crum', 'Walter'),
('328', 'A','Cruveilhier', 'Jean'),
('329', 'A','Cullen', 'William'),
('330', 'A','Cumming', 'James'),
('331', 'A','Cunha', 'José Anastacio da'),
('332', 'A','Cuvier', 'Frédéric'),
('333', 'A','Cuvier', 'Georges'),
('334', 'A','Dalencé (d\'Alencé)', 'Joachim'),
('335', 'A','Dalibard', 'Thomas François'),
('336', 'A','Dalton', 'John'),
('337', 'A','Dandelin', 'Germinal Pierre'),
('338', 'A','Daniell', 'John Frederic'),
('339', 'A','Darcet [d\'Arcet]', 'Jean'),
('340', 'A','Darcy [d\'Arcy]', 'Patrick'),
('341', 'A','Darlington', 'William'),
('342', 'A','Darwin', 'Erasmus'),
('343', 'A','Daubenton', 'Louis-Jean-Marie'),
('344', 'A','Daubeny', 'Charles Giles Bridle'),
('345', 'A','Davy', 'Humphry'),
('346', 'A','Davy', 'John'),
('347', 'A','Dawes', 'William Rutter'),
('351', 'A','Dechen', 'Heinrich von'),
('348', 'A','De la Beche', 'Henry Thomas'),
('352', 'A','Delafosse', 'Gabriel'),
('353', 'A','Delambre', 'Jean-Baptiste Joseph'),
('354', 'A','Delile (Raffeneau-Delile)', 'Alire'),
('355', 'A','Delisle', 'Guillaume'),
('356', 'A','Delisle (Delil)', 'Joseph-Nicolas'),
('357', 'A','Della Torre', 'Giovanni Maria'),
('358', 'A','Deluc', 'Jean-André'),
('359', 'A','Denis', 'Jean-Baptiste'),
('360', 'A','Deparcieux', 'Antoine'),
('361', 'A','Derham', 'William'),
('362', 'A','Derosne', 'Charles'),
('363', 'A','Desaguliers', 'John Theophilus (Jean Théophile)'),
('364', 'A','Descourtilz', 'Michel Etienne'),
('365', 'A','Deshayes', 'Gerard Paul'),
('366', 'A','Desmarest', 'Nicolas'),
('367', 'A','Desormes', 'Charles-Bernard'),
('368', 'A','Dessaignes', 'Victor'),
('369', 'A','Diderot', 'Denis'),
('370', 'A','Dillenius', 'Johann Jacob'),
('371', 'A','Dionis du Séjour', 'Achille-Pierre'),
('372', 'A','Dirichlet', 'Gustav Peter Lejeune'),
('373', 'A','Divis (Divisch)', 'Prokop'),
('374', 'A','Dixon', 'Jeremiah'),
('375', 'A','Döbereiner', 'Johann Wolfgang'),
('376', 'A','Dodart', 'Denis'),
('377', 'A','Döllinger', 'Ignaz'),
('378', 'A','Dollond', 'John'),
('379', 'A','Dolomieu', 'Dieudonné de Gratet de'),
('380', 'A','Dombey', 'Joseph'),
('381', 'A','Doppelmayr (Doppelmeyer)', 'Johann Gabriel'),
('382', 'A','Doppler', 'Johann Christian'),
('383', 'A','Douglas', 'James I'),
('384', 'A','Dove', 'Heinrich Wilhelm'),
('385', 'A','Draparnaud', 'Jacques-Philippe-Raymond'),
('386', 'A','Du Buat', 'Pierre-Louis-Georges'),
('388', 'A','Dufay', 'Charles-François de Cisternay'),
('389', 'A','Dufour', 'Guillaume-Henri'),
('390', 'A','Dufrénoy (Petit-Dufrénoy)', 'Ours-Pierre-Armand'),
('387', 'A','Du Hamel', 'Jean-Baptiste'),
('391', 'A','Duhamel', 'Jean-Marie-Constant'),
('392', 'A','Duhamel du Monceau', 'Henri-Louis'),
('393', 'A','Dujardin', 'Félix'),
('394', 'A','Dulong', 'Pierre Louis'),
('395', 'A','Dumas', 'Jean-Baptiste-André'),
('396', 'A','Duméril', 'André-Marie-Constant'),
('397', 'A','Dundonald (Cochrane)', 'Archibald Cochrane, earl of'),
('398', 'A','Dunglison', 'Robley'),
('399', 'A','Duperrey', 'Louis-Isidore'),
('400', 'A','Dupin', 'Pierre-Charles-François, baron'),
('401', 'A','Dutrochet', 'René-Joachim-Henri'),
('402', 'A','Duverney (Du Verney)', 'Joseph-Guichard'),
('403', 'A','Dyadkovsky', 'Iustin Evdokimovich'),
('404', 'A','Eaton', 'Amos'),
('405', 'A','Ebel', 'Johann Gottfried'),
('406', 'A','Edwards', 'William Frederic'),
('407', 'A','Ehrenberg', 'Christian Gottfried'),
('408', 'A','Ehret', 'Georg Dionysius'),
('409', 'A','Eichwald', 'Karl Eduard Ivanovich'),
('410', 'A','Ekeberg', 'Anders Gustaf'),
('411', 'A','Elhuyar y Lubice', 'Fausto d\''),
('412', 'A','Elhuyar y Lubice', 'Juan José d\''),
('413', 'A','Elie de Beaumont', 'Jean-Baptiste-Armand-Léonce'),
('414', 'A','Eller von Brockhausen', 'Johann Theodor'),
('415', 'A','Emmons', 'Ebenezer'),
('416', 'A','Encke', 'Johann Franz'),
('417', 'A','Erdmann', 'Otto Linné'),
('418', 'A','Escher von der Linth', 'Hans Conrad'),
('419', 'A','Eschscholtz', 'Johann Friedrich'),
('420', 'A','Espy', 'James Pollard'),
('421', 'A','Euler', 'Leonhard'),
('422', 'A','Evans', 'Lewis'),
('423', 'A','Evelyn', 'John'),
('424', 'A','Eytelwein', 'Johann Albert C.'),
('425', 'A','Fabbroni', 'Giovanni Valentino Mattia'),
('426', 'A','Fabricius', 'Johann Christian'),
('427', 'A','Fagnano dei Toschi', 'Giovanni Francesco'),
('428', 'A','Fagnano dei Toschi', 'Giulio Carlo'),
('429', 'A','Fahrenheit', 'Daniel Gabriel'),
('430', 'A','Faraday', 'Michael'),
('431', 'A','Farey', 'John'),
('432', 'A','Farrar', 'John'),
('433', 'A','Faujas de Saint-Fond', 'Barthélemy'),
('434', 'A','Featherstonhaugh', 'George William'),
('435', 'A','Fechner', 'Gustav Theodor'),
('436', 'A','Fée', 'Antoine-Laurent-Apollinaire'),
('437', 'A','Ferguson', 'James'),
('438', 'A','Ferrein', 'Antoine'),
('439', 'A','Feuerbach', 'Karl Wilhelm'),
('440', 'A','Fischer', 'Nicolaus Wolfgang'),
('441', 'A','Fitton', 'William Henry'),
('442', 'A','Fitzroy', 'Robert'),
('443', 'A','Flamsteed', 'John'),
('444', 'A','Fleming', 'John'),
('445', 'A','Flourens', 'Marie-Jean-Pierre'),
('446', 'A','Folkes', 'Martin'),
('447', 'A','Fontaine (des Bertins)', 'Alexis'),
('448', 'A','Fontana', 'Felice'),
('449', 'A','Fontenelle', 'Bernard le Bovier de'),
('450', 'A','Forchhammer', 'Johan Georg'),
('451', 'A','Forsskal [Forskal]', 'Peter'),
('452', 'A','Forster', 'Johann Georg Adam'),
('453', 'A','Forster', 'Johann Reinhold'),
('454', 'A','Fortin', 'Jean Nicolas'),
('455', 'A','Foster', 'Henry'),
('456', 'A','Fouchy', 'Jean Paul Grandjean de'),
('457', 'A','Fourcroy', 'Antoine François de'),
('458', 'A','Fourier', 'Jean Baptiste Joseph'),
('460', 'A','Français', 'François (Joseph)'),
('461', 'A','Français', 'Jacques-Frédéric'),
('462', 'A','Frankenheim', 'Moritz Ludwig'),
('463', 'A','Franklin', 'Benjamin'),
('464', 'A','Fraunhofer', 'Joseph'),
('465', 'A','Freiesleben', 'Johann Karl'),
('466', 'A','Freind', 'John'),
('467', 'A','Frere', 'John'),
('468', 'A','Fresnel', 'Augustin J.'),
('469', 'A','Fries', 'Elias Magnus'),
('470', 'A','Fries', 'Jacob Friedrich'),
('471', 'A','Frisi', 'Paolo'),
('472', 'A','Fuchs', 'Johann Nepomuk von'),
('473', 'A','Füchsel', 'Georg Christian'),
('474', 'A','Fuhlrott', 'Johann Karl'),
('475', 'A','Fuss (Fus)', 'Nikolaus von (Nikolai Ivanovich)'),
('476', 'A','Gadolin', 'Johan'),
('477', 'A','Gaertner (Gärtner)', 'Joseph'),
('478', 'A','Gaertner (Gärtner)', 'Karl Friedrich von'),
('479', 'A','Gagliardi', 'Domenico'),
('480', 'A','Gahn', 'Johan Gottlieb'),
('481', 'A','Gaimard', 'Joseph Paul'),
('482', 'A','Galeazzi (Galeati)', 'Domenico Gusmano'),
('483', 'A','Gall', 'Franz Joseph'),
('484', 'A','Gallois', 'Jean'),
('485', 'A','Galvani', 'Luigi'),
('486', 'A','Gambey', 'Henri-Prudence'),
('487', 'A','Garnett', 'Thomas'),
('488', 'A','Garnot', 'Prosper'),
('489', 'A','Gassiot', 'John Peter'),
('490', 'A','Gaudin', 'Marc Antoine Augustin'),
('491', 'A','Gaultier de Claubry', 'Henri-François'),
('492', 'A','Gauss', 'Carl Friedrich'),
('493', 'A','Gay-Lussac', 'Joseph Louis'),
('494', 'A','Geer (De Geer)', 'Charles de (Carl de)'),
('495', 'A','Gehlen', 'Adolf Ferdinand'),
('498', 'A','Geoffroy [Geoffroy le cadet]', 'Claude Joseph'),
('497', 'A','Geoffroy [Geoffroy l\'aîné]', 'Etienne-François'),
('496', 'A','Geoffroy', 'Etienne-Louis'),
('499', 'A','Geoffroy Saint-Hilaire', 'Etienne'),
('500', 'A','Geoffroy Saint-Hilaire', 'Isidore'),
('501', 'A','Gerbezius [Gerbec]', 'Marcus [Marko]'),
('502', 'A','Gergonne', 'Joseph Diaz'),
('503', 'A','Germain', 'Sophie'),
('504', 'A','Gessner', 'Johannes'),
('505', 'A','Ghisi', 'Martino'),
('506', 'A','Girard', 'Pierre-Simon'),
('507', 'A','Girtanner', 'Christoph'),
('508', 'A','Gleichen-Russworm', 'Wilhelm Friedrich von'),
('509', 'A','Gmelin', 'Johann Georg (II)'),
('510', 'A','Gmelin', 'Leopold'),
('511', 'A','Godfrey', 'Thomas'),
('512', 'A','Godin', 'Louis'),
('513', 'A','Goeppert (Göppert)', 'Heinrich Robert'),
('514', 'A','Goethe', 'Johann Wolfgang von'),
('515', 'A','Goldbach', 'Christian'),
('516', 'A','Gompertz', 'Benjamin'),
('517', 'A','Goodricke', 'John'),
('518', 'A','Gould', 'Augustus Addison'),
('519', 'A','Gould', 'John'),
('520', 'A','Gräffe (Graeffe)', 'Karl Heinrich'),
('521', 'A','Graham', 'George'),
('522', 'A','Graham', 'Thomas'),
('523', 'A','Grandi', 'Guido'),
('524', 'A','Gravesande (\'sGravesande)', 'Willem Jacob \'s'),
('525', 'A','Gray', 'Stephen'),
('526', 'A','Green', 'George'),
('527', 'A','Green', 'Jacob'),
('528', 'A','Greenough', 'George Bellas'),
('529', 'A','Greenwood', 'Isaac'),
('530', 'A','Gregory', 'David'),
('531', 'A','Gregory', 'Olinthus Gilbert'),
('532', 'A','Gregory', 'William'),
('533', 'A','Gren', 'Friedrich Albrecht Carl'),
('534', 'A','Grew', 'Nehemiah'),
('535', 'A','Griffith', 'Richard John'),
('536', 'A','Grotthuss', 'Theodor von (Christian Johann Dietrich)'),
('537', 'A','Grubb', 'Thomas'),
('538', 'A','Gua de Malves', 'Jean Paul de'),
('539', 'A','Gudermann', 'Christoph'),
('540', 'A','Guettard', 'Jean-Etienne'),
('541', 'A','Guyton de Morveau', 'Louis Bernard'),
('542', 'A','Gyllenhaal', 'Leonhard'),
('543', 'A','Hachette', 'Jean Nicolas Pierre'),
('544', 'A','Hadley', 'John'),
('545', 'A','Hahnemann', 'Christian Friedrich Samuel'),
('546', 'A','Haidinger', 'Wilhelm Karl von'),
('547', 'A','Hale', 'William'),
('548', 'A','Hales', 'Stephen'),
('549', 'A','Hall', 'James (Sir)'),
('550', 'A','Hall', 'Marshall'),
('551', 'A','Haller', 'Albrecht von'),
('552', 'A','Halley', 'Edmund'),
('553', 'A','Hamilton', 'Sir William'),
('554', 'A','Hamilton', 'William'),
('555', 'A','Hamilton', 'William Rowan'),
('556', 'A','Hansen', 'Peter Andreas'),
('557', 'A','Hansteen', 'Christopher'),
('558', 'A','Harding', 'Carl Ludwig'),
('559', 'A','Hare', 'Robert'),
('560', 'A','Harlan', 'Richard'),
('561', 'A','Harris', 'John'),
('562', 'A','Harrison', 'John'),
('563', 'A','Hartig', 'Theodor'),
('564', 'A','Hartley', 'David'),
('565', 'A','Hartmann', 'Carl Friedrich Alexander'),
('566', 'A','Hartsoeker', 'Nicolaas'),
('567', 'A','Hassenfratz', 'Jean-Henri'),
('568', 'A','Hassler', 'Ferdinand Rudolph'),
('569', 'A','Hatchett', 'Charles'),
('570', 'A','Hauksbee (Hawksbee)', 'Francis'),
('571', 'A','Hauksbee', 'Francis II'),
('574', 'A','Haworth', 'Adrian Hardy'),
('575', 'A','Hecht', 'Daniel Friedrich'),
('576', 'A','Hedwig', 'Johann'),
('577', 'A','Heister', 'Lorenz'),
('578', 'A','Hell (Höll)', 'Maximilian'),
('579', 'A','Hellot', 'Jean'),
('580', 'A','Helmersen', 'Grigory Petrovich'),
('581', 'A','Henckel (Henkel)', 'Johann Friedrich'),
('582', 'A','Henderson', 'Thomas'),
('583', 'A','Henry', 'Joseph'),
('584', 'A','Henry', 'Thomas'),
('585', 'A','Henry', 'William'),
('586', 'A','Henslow', 'John Stevens'),
('587', 'A','Herapath', 'John'),
('588', 'A','Herbart', 'Johann Friedrich'),
('589', 'A','Herbert', 'William'),
('590', 'A','Hermann', 'Jacob'),
('591', 'A','Hermbstaedt', 'Sigismund Friedrich'),
('592', 'A','Herschel', 'Caroline Lucretia'),
('593', 'A','Herschel', 'John Frederick William'),
('594', 'A','Herschel', 'William'),
('595', 'A','Hess [Gess]', 'Germain Henri [German Ivanovic]'),
('596', 'A','Hessel', 'Johann Friedrich Christian'),
('597', 'A','Hewson', 'William'),
('598', 'A','Heynitz', 'Friedrich Anton von'),
('599', 'A','Hiärne (Hjärne)', 'Urban'),
('600', 'A','Higgins', 'Bryan'),
('602', 'A','Hildebrandt', 'Georg Friedrich'),
('603', 'A','Hill', 'John'),
('604', 'A','Hindenburg', 'Carl Friedrich'),
('605', 'A','Hisinger', 'Wilhelm'),
('606', 'A','Hitchcock', 'Edward'),
('607', 'A','Hodgkinson', 'Eaton'),
('608', 'A','Hoëne-Wronski', 'Jozef Maria'),
('609', 'A','Hoeven', 'Jan van der'),
('610', 'A','Hoff', 'Karl Ernst Adolf von'),
('611', 'A','Hoffmann', 'Friedrich le jeune'),
('612', 'A','Holbach', 'Paul Henri Thiry, baron d\''),
('613', 'A','Holbrook', 'John Edwards'),
('614', 'A','Holmboe', 'Bernt Michael'),
('615', 'A','Homberg', 'Wilhelm (Guillaume)'),
('616', 'A','Home', 'Everard'),
('617', 'A','Hooke', 'Robert'),
('618', 'A','Hooker', 'William Jackson'),
('619', 'A','Hope', 'Thomas Charles'),
('620', 'A','Hopkins', 'William'),
('621', 'A','Horner', 'Leonard'),
('622', 'A','Horner', 'William George'),
('623', 'A','Hornsby', 'Thomas'),
('624', 'A','Horrebow', 'Christian'),
('625', 'A','Horrebow', 'Pedr Nielsen (Pedr I)'),
('626', 'A','Hosack', 'David'),
('627', 'A','Huber', 'Johann Jakob'),
('628', 'A','Hudde', 'Jan (Johann)'),
('629', 'A','Hudson', 'William'),
('630', 'A','Humboldt', 'Alexander von'),
('631', 'A','Hume', 'David'),
('632', 'A','Hunter', 'John'),
('633', 'A','Hunter', 'William'),
('634', 'A','Huschke', 'Emil'),
('635', 'A','Hutton', 'Charles'),
('636', 'A','Hutton', 'James'),
('637', 'A','Ingen-Housz', 'Jan'),
('638', 'A','Ino', 'Tadataka'),
('639', 'A','Ivory', 'James'),
('640', 'A','Jackson', 'Charles Thomas'),
('641', 'A','Jacobi', 'Carl Gustav Jacob'),
('642', 'A','Jacobi', 'Moritz Hermann von (Boris Semenovich)'),
('643', 'A','Jacquin', 'Nikolaus Josef von'),
('644', 'A','Jaeger', 'Georg Friedrich'),
('646', 'A','Jameson', 'Robert'),
('647', 'A','Jars (le cadet)', 'Antoine Gabriel'),
('648', 'A','Jayasimha II [Jai Singh]', 'Savai'),
('649', 'A','Jeaurat', 'Edme-Sébastien'),
('650', 'A','Jefferson', 'Thomas'),
('651', 'A','Jenner', 'Edward'),
('652', 'A','Jerrard', 'George Birch'),
('653', 'A','Joblot', 'Louis'),
('654', 'A','Johnson', 'Manuel John'),
('655', 'A','Jones', 'William'),
('656', 'A','Juan y Santacilla', 'Jorge'),
('657', 'A','Juncker', 'Johann'),
('658', 'A','Jussieu', 'Adrien Henri Laurent de'),
('659', 'A','Jussieu', 'Antoine de'),
('660', 'A','Jussieu', 'Antoine-Laurent de'),
('661', 'A','Jussieu', 'Bernard de'),
('662', 'A','Jussieu', 'Joseph de'),
('663', 'A','Justi', 'Johann Heinrich Gottlob von'),
('664', 'A','Kaempfer', 'Engelbert'),
('665', 'A','Kästner (Kaestner)', 'Abraham Gotthelf'),
('666', 'A','Kalm', 'Pehr'),
('667', 'A','Kant', 'Immanuel'),
('668', 'A','Karsten', 'Karl Johann Bernhard'),
('669', 'A','Kater', 'Henry'),
('670', 'A','Keill', 'James'),
('671', 'A','Keill', 'John'),
('672', 'A','Keir', 'James'),
('673', 'A','Kidd', 'John'),
('674', 'A','Kielmeyer', 'Carl Friedrich'),
('675', 'A','Kinnersley', 'Ebenezer'),
('676', 'A','Kirch', 'Christfried'),
('677', 'A','Kirch', 'Christine'),
('678', 'A','Kirch', 'Gottfried'),
('679', 'A','Kirch-Winckelmann', 'Maria Margarethe'),
('680', 'A','Kirchhof (Kirchgof)', 'Konstantin Sigizmundovich (Gottlieb Sigismund Constantin)'),
('681', 'A','Kirwan', 'Richard'),
('682', 'A','Kitaibel', 'Pal'),
('683', 'A','Klaproth', 'Martin Heinrich'),
('684', 'A','Klein', 'Jacob Theodor'),
('685', 'A','Kleist', 'Ewald Georg von'),
('686', 'A','Klingenstierna', 'Samuel'),
('687', 'A','Klügel (Kluegel)', 'Georg Simon'),
('688', 'A','Knight', 'Thomas Andrew'),
('689', 'A','Knorr', 'Georg Wolfgang'),
('690', 'A','Knox', 'Robert'),
('691', 'A','Koelreuter', 'Joseph Gottlieb'),
('692', 'A','König (Koenig)', 'Johann Samuel'),
('694', 'A','Kraft', 'Jens'),
('695', 'A','Kramp', 'Chrétien (Christian)'),
('696', 'A','Krasheninnikov (Kraseninnikov)', 'Stepan Petrovich'),
('697', 'A','Krayenhoff', 'Cornelis Rudolphus Theodorus'),
('698', 'A','Kunckel von Loewenstern', 'Johann'),
('699', 'A','Kunth', 'Carl Sigismund'),
('707', 'A','Lacaille (La Caille)', 'Nicolas-Louis de'),
('708', 'A','Lacépède', 'Bernard Germain Etienne de la Ville-sur Illon, comte de'),
('703', 'A','La Condamine', 'Charles-Marie de'),
('709', 'A','Lacroix', 'Sylvestre François'),
('710', 'A','Laennec', 'Théophile-René-Hyacinthe'),
('711', 'A','Lagny', 'Thomas Fantet de'),
('712', 'A','Lagrange', 'Joseph Louis'),
('704', 'A','La Hire', 'Gabriel-Philippe (Philippe II) de'),
('705', 'A','La Hire', 'Philippe de'),
('713', 'A','Lalande', 'Joseph-Jérôme Lefrançais de'),
('714', 'A','Lamarck', 'Jean Baptiste Pierre Antoine de Monet de'),
('715', 'A','Lambert', 'Johann Heinrich'),
('717', 'A','Lamé', 'Gabriel'),
('718', 'A','Lamétherie (La Métherie)', 'Jean-Claude de'),
('706', 'A','La Mettrie', 'Julien Offray de'),
('719', 'A','Lamont', 'Johann von'),
('720', 'A','Lamouroux', 'Jean Vincent Félix'),
('721', 'A','Lamy', 'Bernard'),
('722', 'A','Lancisi', 'Giovanni Maria'),
('723', 'A','Lancret', 'Michel Ange'),
('724', 'A','Landen', 'John'),
('725', 'A','Landriani', 'Marsilio'),
('726', 'A','Lang (Langius)', 'Karl Nikolaus'),
('727', 'A','Langlois', 'Claude'),
('728', 'A','Laplace', 'Pierre-Simon, marquis de'),
('349', 'A','De la Rive', 'Auguste [Arthur]'),
('350', 'A','De la Rive', '[Charles] Gaspard'),
('729', 'A','Lartet', 'Edouard Armand Isidore Hippolyte'),
('730', 'A','Lassell', 'William'),
('731', 'A','Latreille', 'Pierre-André'),
('732', 'A','Lavoisier', 'Antoine-Laurent'),
('733', 'A','Lawrence', 'William'),
('734', 'A','Lazarev', 'Mikhail Petrovich'),
('743', 'A','Lea', 'Isaac'),
('744', 'A','Leblanc', 'Nicolas'),
('735', 'A','Le Cat', 'Claude-Nicolas'),
('745', 'A','Leeuwenhoek', 'Antoni van'),
('736', 'A','Le Fèvre (Le Fèbvre)', 'Jean'),
('746', 'A','Legallois', 'Julien Jean César'),
('747', 'A','Legendre', 'Adrien-Marie'),
('737', 'A','Legentil de la Galaisière', 'Guillaume-Joseph-Hyacinthe'),
('748', 'A','Lehmann', 'Johann Gottlob'),
('749', 'A','Leibniz', 'Gottfried Wilhelm'),
('753', 'A','Lemery', 'Nicolas'),
('750', 'A','Lemaire', 'Jacques'),
('751', 'A','Lemaire', 'Pierre'),
('752', 'A','Lemery (aîné)', 'Louis'),
('738', 'A','Le Monnier', 'Louis-Guillaume'),
('739', 'A','Le Monnier', 'Pierre-Charles'),
('754', 'A','Lenz', 'Emil Khristianovich (Heinrich Friedrich Emil)'),
('755', 'A','Leonhard', 'Karl Cäsar von'),
('756', 'A','Leonhardi', 'Johann Gottfried'),
('757', 'A','Lepekhin (Lepechin)', 'Ivan Ivanovich'),
('740', 'A','Feuillée', 'Louis'),
('758', 'A','Lereboullet', 'Dominique-Auguste'),
('741', 'A','Le Roy (Leroy cadet)', 'Charles'),
('742', 'A','Le Roy (Leroy l\'aîné)', 'Jean-Baptiste'),
('759', 'A','Lesage', 'Georges-Louis (II)'),
('760', 'A','Leslie', 'John'),
('761', 'A','Lesson', 'René-Primevère'),
('762', 'A','Lesueur', 'Charles-Alexandre'),
('763', 'A','Leuret', 'François'),
('764', 'A','Levaillant (Le Vaillant)', 'François'),
('765', 'A','Lévy', 'Serve-Dieu Abailard, dit Armand'),
('766', 'A','Lewis', 'William'),
('767', 'A','Lexell (Leksel)', 'Anders Johan'),
('700', 'A','L\'Héritier de Brutelle', 'Charles-Louis'),
('701', 'A','L\'Hospital', 'Guillaume-François-Antoine de'),
('702', 'A','L\'Huillier', 'Simon-Antoine-Jean'),
('768', 'A','Lhwyd (Lhuyd)', 'Edward'),
('769', 'A','Lichtenberg', 'Georg Christoph'),
('770', 'A','Lieberkühn', 'Johannes Nathanael'),
('771', 'A','Liebig', 'Justus von'),
('772', 'A','Liesganig', 'Joseph Xaver'),
('773', 'A','Lieutaud', 'Joseph'),
('774', 'A','Lind', 'James'),
('775', 'A','Lindenau', 'Bernhard August von'),
('776', 'A','Lindley', 'John'),
('777', 'A','Link', 'Heinrich Friedrich'),
('778', 'A','Linnaeus (von Linné)', 'Carl'),
('779', 'A','Lister', 'Joseph Jackson'),
('780', 'A','Lister', 'Martin'),
('781', 'A','Litke (Lütke)', 'Fyodor Petrovich (Frédéric Benjamin von)'),
('782', 'A','Lloyd', 'Humphrey'),
('783', 'A','Lobachevsky', 'Nikolai Ivanovich'),
('784', 'A','Locke', 'John'),
('785', 'A','Logan', 'James'),
('786', 'A','Logan', 'William Edmond'),
('787', 'A','Lomonosov (Lomonossov)', 'Mikhail Vasilievich'),
('788', 'A','Lonsdale', 'William'),
('789', 'A','Lorry', 'Anne Charles'),
('790', 'A','Lovits (Lowitz)', 'Johann Tobias (Tovij Egorovic)'),
('791', 'A','Lubbock', 'John William'),
('792', 'A','Lubbock', 'Richard'),
('793', 'A','Lyell', 'Sir Charles'),
('794', 'A','Lyonet', 'Pierre'),
('795', 'A','Macbride', 'David'),
('796', 'A','Macculloch', 'John'),
('797', 'A','Maclaurin', 'Colin'),
('798', 'A','Maclean', 'John'),
('799', 'A','Maclear', 'Thomas'),
('800', 'A','Maclure', 'William'),
('801', 'A','Macquer', 'Pierre Joseph'),
('802', 'A','Mädler', 'Johann Heinrich'),
('803', 'A','Magalotti', 'Lorenzo'),
('804', 'A','Magellan (Magalhaes)', 'Jean-Hyacinthe (Joao Jacinto de)'),
('805', 'A','Magendie', 'François'),
('806', 'A','Magnitsky (Magnicki)', 'Leonty Filippovich'),
('807', 'A','Magnol', 'Pierre'),
('808', 'A','Magnus', 'Heinrich Gustav'),
('809', 'A','Maillet', 'Benoît de'),
('810', 'A','Mairan', 'Jean Jacques d\'Ortous de'),
('811', 'A','Malebranche', 'Nicolas'),
('812', 'A','Malesherbes', 'Chrétien-Guillaume de Lamoignon de'),
('813', 'A','Malfatti', 'Gian Francesco'),
('814', 'A','Malouin', 'Paul-Jacques'),
('815', 'A','Malthus', 'Thomas Robert'),
('816', 'A','Malus', 'Etienne-Louis'),
('817', 'A','Manfredi', 'Eustachio'),
('818', 'A','Mantell', 'Gideon Algernon'),
('819', 'A','Maraldi I', 'Giacomo Filippo'),
('820', 'A','Maraldi II', 'Giovanni Domenico'),
('821', 'A','Marchant', 'Jean'),
('822', 'A','Marggraf', 'Andreas Sigismund'),
('823', 'A','Marsili (Marsigli)', 'Luigi Ferdinando'),
('824', 'A','Marti Franqués (Marti d\'Ardenya)', 'Antonio de'),
('825', 'A','Martin', 'Benjamin'),
('826', 'A','Martinovics', 'Ignac (Ignaz Joseph)'),
('827', 'A','Martius', 'Karl Friedrich Philipp von'),
('828', 'A','Marum', 'Martin (Martinus) van'),
('829', 'A','Mascagni', 'Paolo'),
('830', 'A','Mascheroni', 'Lorenzo'),
('831', 'A','Maseres (Masères)', 'Francis (François)'),
('832', 'A','Maskelyne', 'Nevil'),
('833', 'A','Mason', 'Charles'),
('834', 'A','Mather', 'William Williams'),
('835', 'A','Maupertuis', 'Pierre Louis Moreau de'),
('836', 'A','Mayer', 'Christian'),
('837', 'A','Mayer', 'Johann Tobias I'),
('838', 'A','Mayo', 'Herbert'),
('839', 'A','Méchain', 'Pierre-François-André'),
('840', 'A','Meckel', 'Johann Friedrich (II)'),
('841', 'A','Medicus', 'Friedrich Casimir'),
('842', 'A','Melloni', 'Macedonio'),
('843', 'A','Melvill', 'Thomas'),
('844', 'A','Menghini', 'Vincenzo Antonio'),
('845', 'A','Menuret de Chambaud', 'Jean Jacques'),
('846', 'A','Mesmer', 'Franz Anton'),
('847', 'A','Messier', 'Charles'),
('848', 'A','Meusnier de la Place', 'Jean-Baptiste-Marie-Charles'),
('850', 'A','Meyer', 'Christian Erich Hermann von'),
('851', 'A','Meyer', 'Johann Friedrich'),
('852', 'A','Michaux', 'André'),
('853', 'A','Micheli', 'Pier Antonio'),
('854', 'A','Michell', 'John'),
('855', 'A','Miller', 'Hugh'),
('856', 'A','Miller', 'Philip'),
('857', 'A','Miller', 'William Hallowes'),
('858', 'A','Millington', 'Thomas'),
('859', 'A','Milne-Edwards', 'Henri'),
('860', 'A','Mirbel', 'Charles François Brisseau de'),
('861', 'A','Mitchell', 'Elisha'),
('862', 'A','Mitscherlich', 'Eilhard'),
('863', 'A','Möbius', 'August Ferdinand'),
('864', 'A','Mocino', 'José Mariano'),
('865', 'A','Moench', 'Conrad'),
('866', 'A','Mohl', 'Hugo von'),
('867', 'A','Mohs', 'Friedrich'),
('868', 'A','Moivre', 'Abraham de'),
('869', 'A','Moldenhawer (Moldenhauer)', 'Johann Jacob Paul'),
('870', 'A','Molina', 'Juan Ignacio'),
('871', 'A','Moll', 'Gerard'),
('872', 'A','Mollweide', 'Karl Brandan'),
('873', 'A','Molyneux', 'Samuel'),
('874', 'A','Monge', 'Gaspard'),
('875', 'A','Monnet', 'Antoine-Grimoald'),
('876', 'A','Monro', 'Alexander I [Primus]'),
('877', 'A','Monro', 'Alexander II [Secundus]'),
('878', 'A','Montesquieu', 'Charles-Louis de Secondat, baron de la Brède et de'),
('879', 'A','Montgéry', 'Jacques-Philippe Mérigon de'),
('880', 'A','Montgolfier', 'Etienne Jacques de'),
('881', 'A','Montgolfier', 'Michel Joseph de'),
('882', 'A','Montmort', 'Pierre Rémond de'),
('883', 'A','Montucla', 'Jean Etienne'),
('885', 'A','Morgagni', 'Giambattista'),
('886', 'A','Morichini', 'Domenico Lino'),
('887', 'A','Moro', 'Antonio-Lazzaro'),
('888', 'A','Morse', 'Jedidiah'),
('889', 'A','Morton', 'John'),
('890', 'A','Morton', 'Samuel George'),
('891', 'A','Mosander', 'Carl Gustaf'),
('892', 'A','Mossotti', 'Ottaviano Fabrizio'),
('893', 'A','Mulder', 'Gerardus Johannes (Gerrit Jan)'),
('896', 'A','Müller von Reichenstein', 'Franz (Ferenc)'),
('894', 'A','Müller (Mueller)', 'Johannes Peter'),
('895', 'A','Müller', 'Otto Frederik'),
('897', 'A','Muncke', 'Georg Wilhelm'),
('898', 'A','Muralt', 'Johannes von'),
('899', 'A','Murchison', 'Sir Roderick Impey'),
('900', 'A','Mushet', 'David'),
('901', 'A','Musschenbroek', 'Petrus van'),
('902', 'A','Mutis y Bossio', 'José Celestino Bruno'),
('903', 'A','Nairne', 'Edward'),
('904', 'A','Naumann', 'Karl Friedrich (I)'),
('905', 'A','Navier', 'Claude-Louis-Marie-Henri'),
('906', 'A','Necker de Saussure', 'Louis-Albert'),
('907', 'A','Needham', 'John Turberville'),
('908', 'A','Nees von Esenbeck', 'Christian Gottfried'),
('909', 'A','Neumann', 'Caspar'),
('910', 'A','Neumann', 'Franz Ernst'),
('911', 'A','Newcomen', 'Thomas'),
('912', 'A','Newport', 'George'),
('913', 'A','Newton', 'Isaac'),
('914', 'A','Nicholson', 'William'),
('915', 'A','Nicol', 'William'),
('916', 'A','Nicolai', 'Friedrich Bernhard Gottfried'),
('917', 'A','Niebuhr', 'Carsten'),
('918', 'A','Niepce', 'Joseph (Nicéphore)'),
('919', 'A','Nieuwentijt', 'Bernard'),
('920', 'A','Nobili', 'Leopoldo'),
('921', 'A','Nollet', 'Jean-Antoine'),
('922', 'A','Nuttall', 'Thomas'),
('923', 'A','Oersted', 'Hans Christian'),
('924', 'A','Ohm', 'Georg Simon'),
('925', 'A','Oken', 'Lorenz'),
('926', 'A','Olbers', 'Heinrich Wilhelm Matthias'),
('927', 'A','Olufsen', 'Christian Friis Rottboll'),
('928', 'A','Omalius d\'Halloy', 'Jean Baptiste Julien d\''),
('929', 'A','Orbigny', 'Alcide Charles Victor Dessalines d\''),
('930', 'A','Ostrogradsky', 'Mikhail Vasilievich'),
('931', 'A','Outhier', 'Réginald'),
('932', 'A','Owen', 'Richard'),
('933', 'A','Ozanam', 'Jacques'),
('934', 'A','Pacchioni', 'Antonio'),
('935', 'A','Paley', 'William'),
('936', 'A','Pallas', 'Peter Simon'),
('937', 'A','Pambour', 'François Marie Guyonneau de'),
('938', 'A','Pander', 'Christian Heinrich'),
('939', 'A','Papin', 'Denis'),
('940', 'A','Parent', 'Antoine'),
('941', 'A','Parkinson', 'James'),
('942', 'A','Parkinson', 'Sydney'),
('943', 'A','Parmentier', 'Antoine-Augustin'),
('944', 'A','Parseval des Chênes', 'Marc-Antoine'),
('945', 'A','Parsons, earl of Rosse', 'William'),
('946', 'A','Pavon y Jiménez', 'José Antonio II'),
('948', 'A','Paykull (Paijkull)', 'Gustaf von'),
('949', 'A','Peacock', 'George'),
('950', 'A','Peale', 'Charles Wilson'),
('951', 'A','Peale', 'Rembrandt'),
('952', 'A','Peale', 'Titian Ramsay'),
('953', 'A','Pearson', 'George'),
('954', 'A','Pelletier', 'Bertrand'),
('955', 'A','Pelletier', 'Pierre-Joseph'),
('956', 'A','Peltier', 'Jean Charles Athanase'),
('957', 'A','Pemberton', 'Henry'),
('958', 'A','Pennant', 'Thomas'),
('959', 'A','Péron', 'François'),
('960', 'A','Perronet', 'Jean-Rodolphe'),
('961', 'A','Persoon', 'Christiaan Hendrik'),
('962', 'A','Persoz', 'Jean-François'),
('963', 'A','Petit', 'Alexis Thérèse'),
('964', 'A','Petrov', 'Vasily Vladimorovich*'),
('965', 'A','Peyer', 'Johann Conrad'),
('966', 'A','Peyssonnel', 'Jean André'),
('967', 'A','Pezenas', 'Esprit'),
('968', 'A','Pfaff', 'Johann Friedrich'),
('969', 'A','Philip', 'Alexander Philips Wilson, dit'),
('970', 'A','Philips (Phillips)', 'John'),
('971', 'A','Phillips (Philips)', 'William'),
('972', 'A','Piazzi', 'Giuseppe'),
('973', 'A','Pictet', 'Marc-Auguste'),
('974', 'A','Pigott', 'Edward'),
('975', 'A','Pigott', 'Nathaniel'),
('976', 'A','Pilatre de Rozier', 'Jean-François'),
('977', 'A','Pinel', 'Philippe'),
('978', 'A','Pingré', 'Alexandre-Guy'),
('979', 'A','Pitcairn', 'Archibald'),
('981', 'A','Plana', 'Giovanni'),
('982', 'A','Plateau', 'Joseph Antoine Ferdinand'),
('983', 'A','Plattner', 'Karl Friedrich'),
('984', 'A','Playfair', 'John'),
('985', 'A','Plencic (Plenciz)', 'Marcus Antonius'),
('986', 'A','Pluche', 'Noël-Antoine'),
('987', 'A','Plücker', 'Julius'),
('988', 'A','Plumier', 'Charles'),
('989', 'A','Plummer', 'Andrew'),
('990', 'A','Poggendorff', 'Johann Christian'),
('991', 'A','Poinsot', 'Louis'),
('992', 'A','Poiseuille', 'Jean Léonard Marie'),
('993', 'A','Poisson', 'Siméon-Denis'),
('994', 'A','Poivre', 'Pierre'),
('995', 'A','Poleni', 'Giovanni'),
('996', 'A','Poli', 'Giuseppe Saverio'),
('997', 'A','Polinière', 'Pierre'),
('998', 'A','Pollender', 'Aloys'),
('999', 'A','Poncelet', 'Jean Victor'),
('1000', 'A','Pons', 'Jean-Louis'),
('1001', 'A','Pontedera', 'Giulio'),
('1002', 'A','Porro', 'Ignazio'),
('1003', 'A','Porta', 'Luigi'),
('1004', 'A','Portal', 'Antoine'),
('1005', 'A','Pott', 'Johann Heinrich'),
('1006', 'A','Pouchet', 'Félix Archimède'),
('1007', 'A','Pouillet', 'Claude-Servais-Mathias'),
('1008', 'A','Pourfour du Petit', 'François'),
('1009', 'A','Powell', 'Baden'),
('1010', 'A','Presl', 'Karel Boriwoj'),
('1011', 'A','Prevost', 'Isaac-Bénédict'),
('1012', 'A','Prevost', 'Jean-Louis'),
('1013', 'A','Prévost', 'Louis-Constant'),
('1014', 'A','Prevost', 'Pierre'),
('1015', 'A','Prichard', 'James Cowles'),
('1016', 'A','Priestley', 'Joseph'),
('1017', 'A','Pringle', 'John'),
('1018', 'A','Privat de Molières', 'Joseph'),
('1019', 'A','Prochaska', 'Georgius (Jiri)'),
('1020', 'A','Prony', 'Gaspard-François-Marie Riche de'),
('1021', 'A','Proust', 'Joseph Louis'),
('1022', 'A','Prout', 'William'),
('1023', 'A','Purkyne (Purkinje)', 'Jan Evangelista'),
('1024', 'A','Pursh (Pursch)', 'Frederick (Friedrich Traugott)'),
('1025', 'A','Quetelet', 'Lambert-Adolphe-Jacques'),
('1026', 'A','Quoy', 'Jean-René-Constant'),
('1027', 'A','Raffles', 'Thomas Stamford Bingley'),
('1028', 'A','Rafinesque', 'Constantin Samuel'),
('1029', 'A','Ramond de Carbonnières', 'Louis François Elisabeth, baron'),
('1030', 'A','Ramsden', 'Jesse'),
('1031', 'A','Raspail', 'François-Vincent'),
('1032', 'A','Raspe', 'Rudolf Erich'),
('1033', 'A','Rathke', 'Martin Heinrich'),
('1034', 'A','Ray', 'John'),
('1035', 'A','Réaumur', 'René-Antoine Ferchault de'),
('1036', 'A','Redfield', 'William C.'),
('1037', 'A','Redouté', 'Pierre-Joseph'),
('1038', 'A','Reech', 'Ferdinand'),
('1039', 'A','Reichenbach', 'Georg Friedrich von'),
('1040', 'A','Reichenbach', 'Karl Ludwig von'),
('1041', 'A','Reil', 'Johann Christian'),
('1042', 'A','Rennell', 'James'),
('1043', 'A','Repsold', 'Johann Georg'),
('1044', 'A','Retzius', 'Anders Adolf'),
('1045', 'A','Reuss', 'Franz Ambrosius'),
('1046', 'A','Reyneau', 'Charles René'),
('1047', 'A','Riccati', 'Jacopo Francesco, comte'),
('1048', 'A','Riccati', 'Vincenzo'),
('1049', 'A','Richard', 'Louis Paul Emile'),
('1050', 'A','Richmann', 'Georg Wilhelm'),
('1051', 'A','Richter', 'Jeremias Benjamin'),
('1052', 'A','Rima', 'Tommaso'),
('1053', 'A','Rinman', 'Sven'),
('1054', 'A','Rio (Del Rio)', 'Andrés Manuel del'),
('1055', 'A','Rittenhouse', 'David'),
('1056', 'A','Ritter', 'Johann Wilhelm'),
('1057', 'A','Robinet', 'Jean-Baptiste René'),
('1058', 'A','Robins', 'Benjamin'),
('1059', 'A','Robiquet', 'Pierre-Jean'),
('1060', 'A','Robison', 'John'),
('1061', 'A','Roebuck', 'John'),
('1062', 'A','Roesel von Rosenhof', 'August Johann'),
('1063', 'A','Rogers', 'William Barton'),
('1064', 'A','Rolando', 'Luigi'),
('1065', 'A','Rolle', 'Michel'),
('1066', 'A','Romé de l\'Isle', 'Jean-Baptiste-Louis'),
('1067', 'A','Römer (Roemer)', 'Ole Christensen'),
('1068', 'A','Rose', 'Gustav'),
('1069', 'A','Rose', 'Heinrich'),
('1070', 'A','Rosenberger', 'Otto August'),
('1071', 'A','Ross', 'James Clark'),
('1072', 'A','Rostan', 'Léon Louis'),
('1074', 'A','Rouelle [aîné]', 'Guillaume-François'),
('1075', 'A','Rouelle [cadet]', 'Hilaire-Marin'),
('1076', 'A','Rowning', 'John'),
('1077', 'A','Rudbeck', 'Olof I'),
('1078', 'A','Rudolphi', 'Karl Asmund'),
('1079', 'A','Ruffini', 'Paolo'),
('1080', 'A','Rühmkorff', 'Heinrich Daniel'),
('1081', 'A','Ruiz', 'Hipolito'),
('1084', 'A','Runge', 'Friedlieb Ferdinand'),
('1085', 'A','Rush', 'Benjamin'),
('1086', 'A','Rutherford', 'Daniel'),
('1088', 'A','Sabine', 'Edward'),
('1089', 'A','Saccheri', 'Girolamo (Giovanni)'),
('1090', 'A','Sacco', 'Luigi'),
('1091', 'A','Sage', 'Balthazar-Georges'),
('1092', 'A','Saint-Hilaire', 'Augustin François César Prouvençal, dit'),
('1093', 'A','Saint-Venant', 'Adhémar Jean Claude Barré de'),
('1094', 'A','Santorini', 'Giovanni Domenico'),
('1095', 'A','Sars', 'Michael'),
('1096', 'A','Sarychev', 'Gavril Andreevich'),
('1097', 'A','Sato V', 'Nobuhiro'),
('1098', 'A','Sato III', 'Nobukage'),
('1099', 'A','Sato IV', 'Nobusue'),
('1100', 'A','Saurin', 'Joseph'),
('1101', 'A','Saussure', 'Horace Bénédict de'),
('1102', 'A','Saussure', 'Nicolas-Théodore de'),
('1103', 'A','Sauveur', 'Joseph'),
('1104', 'A','Savart', 'Félix'),
('1105', 'A','Savigny', 'Marie-Jules-César Lelorgne de'),
('1106', 'A','Saxton', 'Joseph'),
('1107', 'A','Say', 'Thomas'),
('1108', 'A','Scarpa', 'Antonio'),
('1109', 'A','Scheele', 'Carl Wilhelm'),
('1110', 'A','Schelling', 'Frederick Wilhelm Joseph [von]'),
('1111', 'A','Scheuchzer', 'Johann Jakob (II)'),
('1112', 'A','Schimper', 'Karl Friedrich'),
('1113', 'A','Schleiden', 'Jacob Mathias'),
('1114', 'A','Schlotheim', 'Ernst Friedrich von'),
('1115', 'A','Schmerling', 'Philippe-Charles'),
('1116', 'A','Schmidel', 'Casimir Christoph'),
('1117', 'A','Schönbein', 'Christian Friedrich'),
('1118', 'A','Schönherr', 'Carl Johan'),
('1119', 'A','Schönlein', 'Johann Lucas'),
('1120', 'A','Schoolcraft', 'Henry Rowe'),
('1121', 'A','Schouw', 'Joakim Frederik'),
('1122', 'A','Schreibers', 'Karl Franz Anton von'),
('1123', 'A','Schroeder van der Kolk', 'Jacobus Ludovicus Conradus'),
('1124', 'A','Schröter (Sreter)', 'Johann Hieronymus (Iogann Ieromin)'),
('1125', 'A','Schrötter', 'Anton von'),
('1126', 'A','Schumacher', 'Heinrich Christian'),
('1127', 'A','Schwabe', 'Samuel Heinrich'),
('1128', 'A','Schweigger', 'Johann Salomo Christoph'),
('1129', 'A','Schweikart', 'Ferdinand Karl'),
('1130', 'A','Scrope', 'George Julius Poulett'),
('1131', 'A','Sedgwick', 'Adam'),
('1132', 'A','Seebeck', 'Thomas'),
('1133', 'A','Segner', 'Janos-Andras (Johann Andreas von)'),
('1134', 'A','Séguin', 'Armand'),
('1135', 'A','Seguin (aîné)', 'Marc'),
('1136', 'A','Seki', 'Takakazu'),
('1137', 'A','Senac', 'Jean-Baptiste'),
('1138', 'A','Senebier', 'Jean'),
('1139', 'A','Serres', 'Antoine Etienne Reynaud Augustin'),
('1140', 'A','Serres de Mesplès', 'Marcel Pierre Toussaint de'),
('1141', 'A','Sertürner', 'Friedrich Wilhelm Adam Ferdinand'),
('1142', 'A','Serullas', 'Georges-Simon'),
('1143', 'A','Servois', 'François-Joseph'),
('1144', 'A','Sessé y Lacasta', 'Martin de'),
('1145', 'A','Severgin', 'Vasily Mihailovich'),
('1146', 'A','Sharpey', 'William'),
('1147', 'A','Shaw', 'Peter'),
('1148', 'A','Sherard', 'William'),
('1149', 'A','Shibukawa (Yasui Santestu II)', 'Harumi'),
('1150', 'A','Shizuki', 'Tadao'),
('1151', 'A','Short', 'James'),
('1152', 'A','Siebold', 'Carl Theodor Ernst von'),
('1153', 'A','Sigaud de Lafond', 'Joseph-Aignan'),
('1154', 'A','Sigorgne', 'Pierre'),
('1155', 'A','Silliman', 'Banjamin sr'),
('1156', 'A','Simpson', 'Thomas'),
('1157', 'A','Simson', 'Robert'),
('1158', 'A','Skoda', 'Josef'),
('1159', 'A','Sloane', 'Sir Hans'),
('1160', 'A','Smeaton', 'John'),
('1161', 'A','Smith', 'James Edward'),
('1162', 'A','Smith', 'Robert'),
('1163', 'A','Smith', 'William'),
('1164', 'A','Smithson', 'James Louis Macie, dit'),
('1165', 'A','Soemmerring (Sömmerring)', 'Samuel Thomas'),
('1166', 'A','Sokolov', 'Dmitry Ivanovich'),
('1167', 'A','Solander', 'Daniel Carl'),
('1168', 'A','Soldani', 'Ambrogio'),
('1169', 'A','Soldner', 'Johann Georg von'),
('1170', 'A','Soleil', 'Jean-Baptiste-François'),
('1171', 'A','Somerville', 'Mary Fairfax Greig'),
('1172', 'A','Sonnerat', 'Pierre'),
('1173', 'A','Soulavie (Giraud-Soulavie)', 'Jean-Louis Giraud'),
('1174', 'A','South', 'James'),
('1175', 'A','Sowerby', 'James'),
('1176', 'A','Spallanzani', 'Lazzaro'),
('1177', 'A','Spix', 'Johann Baptist von'),
('1178', 'A','Sprat', 'Thomas'),
('1179', 'A','Sprengel', 'Christian Konrad'),
('1180', 'A','Sprengel', 'Kurt Polycarp Joachim'),
('1181', 'A','Spurzheim', 'Johann Christoph'),
('1182', 'A','Stahl', 'Georg Ernst'),
('1183', 'A','Staszic', 'Stanislaw Wawrzyniec'),
('1184', 'A','Staudt', 'Karl Georg Christian von'),
('1185', 'A','Steiner', 'Jacob'),
('1186', 'A','Steinheil', 'Karl August'),
('1187', 'A','Steller', 'Georg Wilhelm'),
('1188', 'A','Stepling', 'Joseph'),
('1189', 'A','Sternberg', 'Kaspar Maria von'),
('1190', 'A','Stevens', 'Edward'),
('1191', 'A','Stewart', 'Matthew'),
('1192', 'A','Stirling', 'James'),
('1193', 'A','Strachey', 'John'),
('1194', 'A','Struve', 'Friedrich Georg Wilhelm von (Vasily Yakovlevich)'),
('1195', 'A','Stuart', 'Alexander'),
('1196', 'A','Studer', 'Bernhard'),
('1197', 'A','Sturgeon', 'William'),
('1198', 'A','Sturm', 'Charles-François'),
('1199', 'A','Swainson', 'William'),
('1200', 'A','Swartz', 'Olof'),
('1201', 'A','Swedenborg', 'Emanuel'),
('1202', 'A','Swieten', 'Gerard van'),
('1203', 'A','Swinden', 'Jan Hendrik van'),
('1204', 'A','Symmer', 'Robert'),
('1205', 'A','Talbot', 'William Henry Fox'),
('1206', 'A','Targioni Tozzetti', 'Giovanni'),
('1207', 'A','Taurinus', 'Franz Adolf'),
('1208', 'A','Taylor', 'Brook'),
('1209', 'A','Tennant', 'Smithson'),
('1210', 'A','Thénard', 'Louis Jacques'),
('1211', 'A','Thompson', 'John Vaughan'),
('1212', 'A','Thomsen', 'Christian Jürgensen'),
('1213', 'A','Thomson', 'Thomas'),
('1215', 'A','Thunberg', 'Carl Peter'),
('1216', 'A','Tiedemann', 'Friedrich'),
('1217', 'A','Tilas', 'Daniel'),
('1218', 'A','Tillet', 'Mathieu'),
('1219', 'A','Tilloch', 'Alexander'),
('1220', 'A','Tinseau d\'Amondans', 'Charles de'),
('1221', 'A','Titius (Tietz)', 'Johann Daniel'),
('1222', 'A','Torrey', 'John'),
('1223', 'A','Toulmin', 'George Hoggart'),
('1224', 'A','Tournefort', 'Joseph Pitton de'),
('1225', 'A','Towneley', 'Richard'),
('1226', 'A','Townsend', 'Joseph'),
('1227', 'A','Tozzi', 'Don Bruno'),
('1228', 'A','Trebra', 'Friedrich Wilhelm Heinrich von'),
('1229', 'A','Trembley', 'Abraham'),
('1230', 'A','Treviranus', 'Gottfried Reinhold'),
('1231', 'A','Treviranus', 'Ludolph Christian'),
('1232', 'A','Troja', 'Michele'),
('1233', 'A','Trommsdorff', 'Johann Bartholomäus'),
('1234', 'A','Troost', 'Gerard'),
('1235', 'A','Troostwijk', 'Adriaan Paets van'),
('1236', 'A','Troughton', 'Edward'),
('1237', 'A','Tschirnhaus', 'Ehrenfried Walther, comte de'),
('1238', 'A','Turgot', 'Anne-Robert-Jacques'),
('1239', 'A','Turgot', 'Etienne-François'),
('1240', 'A','Turner', 'Edward'),
('1241', 'A','Turpin', 'Pierre Jean François'),
('1242', 'A','Tyson', 'Edward'),
('1243', 'A','Ulloa de la Torre Giral', 'Antonio de'),
('1244', 'A','Unanue', 'José Hipolito'),
('1245', 'A','Unger', 'Franz'),
('1246', 'A','Unzer', 'Johann August'),
('1247', 'A','Ure', 'Andrew'),
('1248', 'A','Vaillant', 'Sébastien'),
('1249', 'A','Valenciennes', 'Achille'),
('1250', 'A','Vallisnieri (Vallisneri)', 'Antonio'),
('1251', 'A','Valmont de Bomare', 'Jacques-Christophe'),
('1252', 'A','Valsalva', 'Anton Maria'),
('1253', 'A','Vandermonde', 'Alexandre-Théophile (Charles-Auguste)'),
('1254', 'A','Vanuxem', 'Lardner'),
('1255', 'A','Varignon', 'Pierre'),
('1256', 'A','Vauban', 'Sébastien le Prestre de'),
('1257', 'A','Vaucher', 'Jean Pierre Etienne'),
('1258', 'A','Vauquelin', 'Nicolas Louis'),
('1259', 'A','Vellozo', 'José Mariano da Conceiçao'),
('1260', 'A','Venel', 'Gabriel François'),
('1261', 'A','Venetz', 'Ignatz'),
('1262', 'A','Verhulst', 'Pierre-François'),
('1263', 'A','Verneuil', 'Philippe Edouard Poulletier de'),
('1264', 'A','Vicq d\'Azyr', 'Félix'),
('1265', 'A','Vieussens', 'Raymond de'),
('1266', 'A','Vigani', 'John Francis'),
('1267', 'A','Virey', 'Julien-Joseph'),
('1268', 'A','Viviani', 'Vincenzo'),
('1269', 'A','Voigt', 'Johann Carl Wilhelm'),
('1271', 'A','Volta', 'Alessandro'),
('1272', 'A','Voltaire', 'François Marie Arouet, dit'),
('1273', 'A','Voltz', 'Philippe Louis'),
('1274', 'A','Wackenroder', 'Heinrich Wilhelm Ferdinand'),
('1275', 'A','Wagner', 'Rudolph'),
('1276', 'A','Wahlenberg', 'Göran (Georg)'),
('1277', 'A','Walch', 'Johann Ernst Immanuel'),
('1278', 'A','Walker', 'Alexander'),
('1279', 'A','Walker', 'John'),
('1280', 'A','Wallace', 'William'),
('1281', 'A','Wallerius', 'Johan Gottschalk'),
('1282', 'A','Wallis', 'John'),
('1283', 'A','Wargentin', 'Pehr Wilhelm'),
('1284', 'A','Waring', 'Edward'),
('1285', 'A','Waterton', 'Charles'),
('1286', 'A','Watson', 'Hewett Cottrell'),
('1287', 'A','Watson', 'Richard'),
('1288', 'A','Watson', 'William'),
('1289', 'A','Watt', 'James'),
('1290', 'A','Weber', 'Ernst Heinrich'),
('1291', 'A','Weber', 'Wilhelm Eduard'),
('1292', 'A','Webster', 'Thomas'),
('1293', 'A','Wedel', 'Georg Wolfgang'),
('1294', 'A','Wedgwood', 'Josiah'),
('1295', 'A','Weigel', 'Christian Ehrenfried'),
('1296', 'A','Weiss', 'Christian Samuel'),
('1297', 'A','Wells', 'William Charles'),
('1298', 'A','Werner', 'Abraham Gottlob'),
('1299', 'A','Wessel', 'Caspar'),
('1300', 'A','Whateley', 'Richard'),
('1301', 'A','Wheatstone', 'Charles'),
('1302', 'A','Whewell', 'William'),
('1303', 'A','Whiston', 'William'),
('1304', 'A','White', 'Charles'),
('1305', 'A','White', 'Gilbert'),
('1306', 'A','Whitehurst', 'John'),
('1307', 'A','Whytt (Whyte)', 'Robert'),
('1308', 'A','Widmanstätten (Widmanstetter)', 'Aloys Joseph Beck Edler von'),
('1309', 'A','Wied (Neuwied)', 'Maximilian zu'),
('1310', 'A','Wiegleb', 'Johann Christian'),
('1311', 'A','Wilbrand', 'Johann Bernhard'),
('1312', 'A','Wilcke', 'Johan Carl'),
('1313', 'A','Willdenow', 'Karl Ludwig'),
('1314', 'A','Willis', 'Robert'),
('1315', 'A','Wilson', 'Alexander I'),
('1316', 'A','Wilson', 'Alexander'),
('1317', 'A','Wilson', 'Benjamin'),
('1318', 'A','Wilson', 'John, Sir'),
('1319', 'A','Winslow', 'Jacob (Jacques-Bénigne)'),
('1320', 'A','Winthrop', 'John'),
('1321', 'A','Wistar', 'Caspar'),
('1322', 'A','Witham', 'Henry'),
('1323', 'A','Withering', 'William'),
('1324', 'A','Wöhler', 'Friedrich'),
('1325', 'A','Wolff', 'Caspar Friedrich'),
('1326', 'A','Wolff', 'Christian von'),
('1327', 'A','Wollaston', 'Francis'),
('1328', 'A','Wollaston', 'William Hyde'),
('1329', 'A','Woltman', 'Reinhard'),
('1330', 'A','Woodhouse', 'Robert'),
('1331', 'A','Woodward', 'John'),
('1332', 'A','Woulfe', 'Peter'),
('1333', 'A','Wren', 'Christopher'),
('1334', 'A','Wright', 'Thomas'),
('1335', 'A','Young', 'John Richardson'),
('1336', 'A','Young', 'Thomas'),
('1337', 'A','Zach', 'Franz Xaver von'),
('1338', 'A','Zambeccari', 'Giuseppe'),
('1339', 'A','Zanotti', 'Eustachio'),
('1340', 'A','Zeise', 'William Christopher'),
('1341', 'A','Zejszner (Zeuschner)', 'Ludwik'),
('105', 'A','Bernoulli', 'Johann (Jean) III'),
('62', 'A','Banks', 'Joseph'),
('572', 'A','Haüy', 'René-Just'),
('1082', 'A','Rumford (Thompson, comte)', 'Benjamin'),
('1083', 'A','Rumovsky', 'Stepan Iakovlevitch'),
('227', 'A','Camerarius (Camerer)', 'Rudolph Jakob'),
('459', 'A','Fourneyron', 'Benoît'),
('573', 'A','Havers', 'Clopton'),
('601', 'A','Higgins', 'William'),
('645', 'A','Jagannatha', 'Samrat'),
('693', 'A','König (Koenig)', 'Emanuel'),
('849', 'A','Meyen', 'Franz Julius Ferdinand'),
('884', 'A','Méry', 'Jean'),
('947', 'A','Payen', 'Anselme'),
('980', 'A','Pitot', 'Henri'),
('1073', 'A','Rouelle', 'Jean'),
('1087', 'A','Ruysch', 'Frederik'),
('1214', 'A','Thouin', 'André'),
('1270', 'A','Volney', 'Constantin-François de Chasseboeuf, comte de'),
('1358', 'A','Bourdelin', 'Louis-Claude'),
('1459', 'A','Nicole', 'François'),
('1382', 'A','Deslandes', 'André-François Boureau'),
('1411', 'A','Helvetius', 'Jean-Claude-Adrien'),
('1449', 'A','Montigny', 'Etienne Mignot de'),
('1380', 'A','Desfontaines', 'René Louiche-'),
('1479', 'A','Richard', 'Louis Claude Marie'),
('1467', 'A','Percy', 'Pierre-François de'),
('1425', 'A','Larrey', 'Dominique'),
('1428', 'A','Libri-Carucci della Sommaia', 'Guglielmo Brutus, comte'),
('1478', 'A','Richard', 'Achille'),
('1452', 'A','Morin', 'Arthur Jules'),
('1385', 'A','Duvernoy', 'Georges-Louis'),
('1503', 'A','Klug', 'Johann Christoph Friedrich'),
('1371', 'A','Chabert', 'Joseph-Bernard de'),
('1378', 'A','Daru', 'Pierre-Antoine-Bruno'),
('1381', 'A','Desgenettes', 'René Dufriche'),
('1409', 'A','Guglielmini (Guilielmini)', 'Domenico'),
('1435', 'A','Macclesfield', 'George Parker, 2nd earl of'),
('1505', 'A','Tronchin', 'Théodore'),
('1389', 'A','Euler (Èjler)', 'Johann Albrecht'),
('1386', 'A','Eimmart', 'Georg Christoph jr'),
('1519', 'A','Wurzelbau', 'Johann Philipp von'),
('1444', 'A','Michelotti', 'Pietro Antonio'),
('1453', 'A','Mortimer', 'Cromwell'),
('1417', 'A','Jallabert', 'Jean'),
('1416', 'A','Jacquier', 'François'),
('1426', 'A','Le Seur', 'Thomas'),
('1408', 'A','Grischow (Grisov)', 'Augustin Nathanael'),
('1521', 'A','Zanotti', 'Francesco Maria'),
('1359', 'A','Bourgelat', 'Claude'),
('1441', 'A','Meckel', 'Johann Friedrich I'),
('1433', 'A','Lulofs', 'Johann'),
('1484', 'A','Schäffer (Schaeffer)', 'Jakob Christian'),
('1351', 'A','Bevis (Bevans)', 'John'),
('1431', 'A','Lorgna', 'Antonio Maria'),
('1493', 'A','Spielmann', 'Jakob Reinhold'),
('1442', 'A','Melander (Melanderhjelm)', 'Daniel'),
('1502', 'A','Trembley', 'Jean'),
('1462', 'A','Oriani', 'Barnaba'),
('1509', 'A','Vassalli-Eandi', 'Antonio Maria'),
('1424', 'A','Krusenstern [Kruzenstern]', 'Adam Johann von [Ivan Fedorovic]'),
('1445', 'A','Moll', 'Karl Maria Ehrenbert von'),
('1512', 'A','Viborg', 'Erik Nissen'),
('1355', 'A','Bohnenberger', 'Johann Gottlieb Friedrich von'),
('1498', 'A','Thaer', 'Albrecht Daniel'),
('1494', 'A','Stromeyer', 'Friedrich II'),
('1414', 'A','Hufeland', 'Christoph Wilhelm'),
('1401', 'A','Gaudichaud-Beaupré', 'Charles'),
('1514', 'A','Wallich', 'Nathanael'),
('1384', 'A','Dugès', 'Antoine'),
('1368', 'A','Carlini', 'Francesco'),
('1497', 'A','Temminck', 'Coenraad Jacob'),
('1410', 'A','Hausmann', 'Johann Friedrich Ludwig'),
('1369', 'A','Carus', 'Carl Gustav'),
('1357', 'A','Bourdelin', 'Claude II'),
('1432', 'A','Louville', 'Jacques-Eugène d\'Allonville de'),
('1468', 'A','Petit', 'Jean-Louis'),
('1415', 'A','Hunauld', 'François-Joseph'),
('1360', 'A','Breyne (Breynius)', 'Johann Philipp'),
('1450', 'A','Morand', 'Jean-François-Clément'),
('1349', 'A','Berthoud', 'Ferdinand'),
('1377', 'A','Damoiseau de Montfort', 'Marie-Charles-Théodore, baron de'),
('1383', 'A','Despretz', 'César Mansuète'),
('1475', 'A','Quesnay', 'François'),
('1471', 'A','Poissonnier', 'Pierre-Isaac'),
('1466', 'A','Pembroke', 'Thomas Herberg, earl of'),
('1370', 'A','Cervi', 'Giuseppe'),
('1352', 'A','Bianchini (Blanchinus)', 'Francesco'),
('1375', 'A','Cooper (Cowper)', 'William'),
('1413', 'A','Hotton', 'Petrus'),
('1469', 'A','Petiver', 'James'),
('1372', 'A','Cheselden', 'William'),
('1398', 'A','Garcin', 'Laurent'),
('1501', 'A','Torres', 'Ignacio José de'),
('1350', 'A','Bertier', 'Etienne-Joseph, père'),
('1373', 'A','Chevalier', 'Jean-Baptiste'),
('1495', 'A','Struÿck (Struijck)', 'Nicolaas'),
('1342', 'A','Abeille', 'Louis-Paul'),
('1397', 'A','Bon de Saint-Hilaire', 'François-Xavier'),
('1440', 'A','Mazéas', 'Guillaume'),
('1506', 'A','Turbilly', 'Louis-François-Henri de Menon de'),
('1391', 'A','Ferner (Ferrner)', 'Bengt'),
('1456', 'A','Müller (Miller)', 'Gerhard Friedrich (Fedor Ivanovich)'),
('1344', 'A','Allamand', 'Jean-Nicolas Sébastien'),
('1463', 'A','Ortega', 'Casimiro Gomez'),
('1470', 'A','Poczobut', 'Martin Odlanicki'),
('1365', 'A','Bugge', 'Thomas'),
('1491', 'A','Simmons', 'Samuel Foart'),
('1443', 'A','Mendoza y Rios', 'Don José'),
('1455', 'A','Mudge', 'William'),
('1472', 'A','Pond', 'John'),
('716', 'A','Lambton', 'William'),
('1353', 'A','Blane', 'Gilbert'),
('1363', 'A','Brunel', 'Marc Isambard'),
('1488', 'A','Scoresby', 'William'),
('1374', 'A','Cooper', 'Astley Paston, Sir'),
('1492', 'A','Smyth', 'William Henry'),
('1396', 'A','Franklin', 'Sir John'),
('1454', 'A','Moseley', 'Henry'),
('1343', 'A','Algarotti', 'Francesco, comte'),
('1356', 'A','Cerati', 'Gaspare'),
('1364', 'A','Büchner', 'Andreas Elias'),
('1387', 'A','Erman', 'Paul'),
('1405', 'A','Golicyn (Galitzin; Golitzin)', 'Dmitrij Alexeevic'),
('1436', 'A','Maffei', 'Scipione'),
('1438', 'A','Marinoni', 'Giovanni Jacopo (Johann Jacob von)'),
('1439', 'A','Maty (Matty)', 'Matthew'),
('1458', 'A','Naudé', 'Philippe (le jeune)'),
('1473', 'A','Pontécoulant', 'Philippe-Gustave Doulcet de'),
('1474', 'A','Prinsep', 'James'),
('1476', 'A','Raulin', 'Joseph'),
('1477', 'A','Redern', 'Sigismund Ehrenreich von'),
('1481', 'A','Ritter', 'Karl'),
('1483', 'A','Sauvages de la Croix', 'François Boissier de'),
('1448', 'A','Beccari', 'Jacopo Bartolomeo'),
('1489', 'A','Seip', 'Johann Philipp'),
('1490', 'A','Sellius', 'Gottfried'),
('1496', 'A','Superville', 'Daniel de'),
('1500', 'A','Toaldo', 'Giuseppe'),
('1504', 'A','Trew', 'Christoph Jakob'),
('1508', 'A','Valentini', 'Michael Bernhard'),
('1510', 'A','Vater', 'Abraham'),
('1511', 'A','Lichtenstein', 'Martin Heinrich Karl'),
('1513', 'A','Vigors', 'Nicholas Aylward'),
('1515', 'A','Walmesley', 'Charles'),
('1516', 'A','Walter', 'Johann Gottlieb'),
('1517', 'A','Weidler', 'Johann Friedrich'),
('1451', 'A','Morand', 'Sauveur-François'),
('1379', 'A','Delisle de la Croyère', 'Louis'),
('1482', 'A','Rochon', 'Alexis-Marie de'),
('1366', 'A','Burckhardt', 'Johann Karl'),
('1446', 'A','Hérissant', 'François David'),
('1447', 'A','Montalembert', 'Marc-René, marquis de'),
('1465', 'A','Patrin', 'Eugène-Louis-Melchior'),
('1395', 'A','Francoeur', 'Louis-Benjamin'),
('1507', 'A','Vaillant', 'Jean-Baptiste-Philibert de'),
('1399', 'A','Gaubil', 'Antoine'),
('1520', 'A','Ximenes', 'Leonardo'),
('1437', 'A','Mallet-Favre', 'Jacques-André'),
('1394', 'A','Fossombroni', 'Vittorio, comte'),
('1429', 'A','Littrow (Littrov)', 'Joseph Johann (Joseph Samuel) von'),
('1464', 'A','Parry', 'Sir William Edward'),
('1518', 'A','Wrangell (Vrangel)', 'Ferdinand Ludwig von'),
('1461', 'A','Nordmann', 'Alexander von'),
('1434', 'A','Tressan', 'Louis Elisabeth de La Vergne de'),
('1347', 'A','Baeyer', 'Johann Jakob von'),
('1354', 'A','Böhmer', 'Philipp Adolf'),
('1361', 'A','Brera', 'Valeriano Luigi'),
('1367', 'A','Burja', 'Abel'),
('1388', 'A','Eschricht', 'Daniel Frederik'),
('1390', 'A','Ferber', 'Johann Jakob'),
('1392', 'A','Fischer [Fiser]', 'Friedrich Ernst Ludwig von [Feodor Bogdanovic]'),
('1393', 'A','Fischer von Waldheim', 'Johann Gotthelf (Grigori Ivanovitch)'),
('1402', 'A','Georgi', 'Johann Gottlieb (Ivan Ivanovich)'),
('1403', 'A','Gilbert', 'Ludwig Wilhelm'),
('1404', 'A','Gleditsch', 'Johann Gottlieb'),
('1418', 'A','Kämtz', 'Ludwig Friedrich (Ludwig Martinovitch)'),
('1419', 'A','Razumovski', 'Kirill Grigorievich'),
('1420', 'A','Kies', 'Johannes'),
('1422', 'A','Krafft (Kraft)', 'Georg Wolfgang'),
('1423', 'A','Kratzenstein', 'Christian Gottlieb'),
('1427', 'A','Ledebour (Ledebur)', 'Karl Friedrich'),
('1430', 'A','Loder', 'Justus Christian von'),
('1460', 'A','Nitzsch', 'Christian Ludwig'),
('1480', 'A','Riess', 'Peter Theophil'),
('1485', 'A','Schlegel', 'Hermann'),
('1487', 'A','Schulze (Schultze)', 'Johann Heinrich'),
('1499', 'A','Tilesius von Tilenau', 'Wilhelm Gottlob von'),
('1522', 'A','Zimmermann', 'Eberhard August Wilhelm von'),
('1523', 'A','Zimmermann', 'Johann Georg von'),
('1345', 'A','Ammann', 'Johannes (II)'),
('1346', 'A','Aubert', 'Alexander'),
('1348', 'A','Bergius', 'Peter Jonas'),
('1362', 'A','Brühl', 'Hans Moritz von'),
('1376', 'A','Crichton', 'Alexander'),
('1400', 'A','Gaubius (Gaub)', 'Hieronymus David'),
('1406', 'A','Gorter', 'David de'),
('1407', 'A','Granville', 'Augustus Bozzi, dit'),
('1412', 'A','Horsburgh', 'James'),
('1421', 'A','König', 'Karl (Charles) Dietrich Eberhard'),
('1457', 'A','Musin-Pushkin (Mussin-)', 'Apollos Apollosovitch'),
('1486', 'A','Schreber', 'Johann Christian Daniel von'),
('1524', 'A','Afzelius', 'Adam Arvidson'),
('1525', 'A','Albers', 'Johann Abraham'),
('1526', 'A','Allioni', 'Carlo'),
('1527', 'A','Balbis', 'Giovanni Battista'),
('1528', 'A','Bazaine (Bazen)', 'Pierre Dominique'),
('1529', 'A','Béguillet', 'Edme'),
('1530', 'A','Belgrado (Bellogradus)', 'Jacopo (Jacobus)'),
('1531', 'A','Bertrand', 'Elie'),
('1532', 'A','Bianchi', 'Giovanni Battista'),
('1533', 'A','Bilffinger (Bülfinger)', 'Georg Bernhard'),
('1534', 'A','Billberg', 'Gustaf Johan'),
('1535', 'A','Blume', 'Carl Ludwig (Karel Lodewijk)'),
('1536', 'A','Bourgoing', 'Jean-François de'),
('1537', 'A','Brougham', 'Peter Henry'),
('1538', 'A','Brugnatelli', 'Luigi Valentino'),
('1539', 'A','Copland', 'James'),
('1540', 'A','Crivelli', 'Giovanni'),
('1541', 'A','Dalrymple', 'Alexander'),
('1542', 'A','Darcet (D\'Arcet)', 'Jean-Pierre Joseph'),
('1543', 'A','Daviel', 'Jacques'),
('1544', 'A','Donati', 'Vitaliano'),
('1545', 'A','Dufour', 'Léon'),
('1546', 'A','Dupuytren', 'Guillaume'),
('1547', 'A','Ellicott', 'John'),
('1548', 'A','Expilly', 'Jean-Joseph d\''),
('1549', 'A','Flauti', 'Vincenzo'),
('1550', 'A','Fontana', 'Gregorio'),
('1551', 'A','Fontanieu', 'Pierre-Elisabeth de'),
('1552', 'A','Fougeroux de Bondaroy', 'Auguste-Denis'),
('1553', 'A','Gesner', 'Johann Albrecht'),
('1555', 'A','Gouan', 'Antoine'),
('1556', 'A','Gunner (Gunnerus)', 'Johan Ernst'),
('1557', 'A','Günz', 'Justus Gottfried'),
('1558', 'A','Hee', 'Christen'),
('1559', 'A','Hemmer', 'Johann Jacob'),
('1560', 'A','Héricart de Thury', 'Louis Etienne François'),
('1561', 'A','Hermann [German]', 'Benedict Franz Johann von [Ivan Filippovic]'),
('1562', 'A','Hombres-Firmas', 'Augustin d\''),
('1563', 'A','Hundertmark', 'Carl Friedrich'),
('1564', 'A','Jablonowski', 'Joseph Alexander'),
('1565', 'A','Jacobson', 'Ludwig Lewin'),
('1566', 'A','Jacquin', 'Joseph Franz von'),
('1567', 'A','Kirby', 'William'),
('1568', 'A','La Billardière', 'Jacques-Julien Houtou de'),
('1569', 'A','La Peyronie', 'François Gigot de'),
('1570', 'A','La Tourrette (La Tourette)', 'Marc-Antoine-Louis Claret de Fleurieu de'),
('1571', 'A','Lassone', 'Joseph-Marie-François de'),
('1572', 'A','Latham', 'John'),
('1573', 'A','Laxman [Laksman]', 'Eric [Kirill Gustsvovic]'),
('1574', 'A','Leach', 'William Elford'),
('1575', 'A','Linck', 'Johann Heinrich I'),
('1576', 'A','Malaguti', 'Faustino Giovita Mariano'),
('1577', 'A','Malvezzi (Bonfioli-Malvezzi)', 'Alfonso Bonfioli, dit'),
('1578', 'A','Mannerheim [Mannergejm]', 'Carl Gustav'),
('1579', 'A','Marianini', 'Stefano Giovanni'),
('1580', 'A','Maton', 'William George'),
('1581', 'A','Mayer', 'Andreas'),
('1582', 'A','Meyer', 'Johann Karl Friedrich'),
('1583', 'A','Molinelli', 'Pietro Paolo'),
('1584', 'A','Morozzo della Rocca', 'Carlo Ludovico'),
('1585', 'A','Nordenskjöld', 'Nils Gustav'),
('1586', 'A','Otto', 'Adolf Wilhelm'),
('1587', 'A','Panizza', 'Bartolomeo'),
('1588', 'A','Paoli', 'Pietro'),
('1589', 'A','Petit', 'Antoine'),
('1590', 'A','Psilanderhjelm', 'Nils'),
('1591', 'A','Ratte', 'Etienne-Hyacinthe de'),
('1592', 'A','Rayer', 'Pierre François Olive'),
('1593', 'A','Ridolfi', 'Cosimo, marquis'),
('1594', 'A','Rokitanski', 'Karl von'),
('1595', 'A','Roland de la Platière', 'Jean-Marie'),
('1596', 'A','Roncalli-Parolino', 'Francesco'),
('1597', 'A','Rougier de la Bergerie', 'Jean-Baptiste'),
('1598', 'A','Formey', 'Jean Henri Samuel'),
('1599', 'A','Rozier', 'Jean François'),
('1600', 'A','Sabine', 'Joseph'),
('1601', 'A','Santini', 'Giovanni'),
('1602', 'A','Savi', 'Gaetano'),
('1603', 'A','Scheuchzer', 'Johann'),
('1604', 'A','Schrader', 'Heinrich Adolf'),
('1605', 'A','Schultén', 'Nathanael Gerhard I af'),
('1606', 'A','Sefström', 'Nils Gabriel'),
('1607', 'A','Séguier', 'Jean-François'),
('1608', 'A','Selle', 'Christian Gottlieb'),
('1609', 'A','Sinclair', 'John'),
('1610', 'A','Steven', 'Christian von'),
('1611', 'A','Sundevall', 'Carl Jakob'),
('1612', 'A','Svanberg (Swanberg)', 'Jöns'),
('1613', 'A','Telford', 'Thomas'),
('1614', 'A','Tenore', 'Michele'),
('1615', 'A','Trinius', 'Karl Bernhard von'),
('1616', 'A','Velpeau', 'Alfred Armand Louis'),
('1617', 'A','Viviani', 'Domenico'),
('1618', 'A','Zinn', 'Johann Gottfried'),
('1554', 'A','Correa da Serra', 'José Francesco'),
('1619', 'A','Beaufort', 'Francis, Sir'),
('1628', 'A','Jaucourt', 'Louis de'),
('1620', 'A','Brunacci', 'Vincenzo'),
('1621', 'A','Cagnoli', 'Antonio'),
('1622', 'A','Cline', 'Henry'),
('1623', 'A','Delaval', 'Edward Hussey'),
('1624', 'A','Fairbairn', 'William'),
('1625', 'A','Florman', 'Arvid Henrik'),
('1626', 'A','Fortis', 'Giovanni Battista, dit Alberto'),
('1627', 'A','Gray', 'John Edward'),
('1629', 'A','Kupffer (Kupfer)', 'Adolph Theodor von (Adolf Jakovlevich)'),
('1630', 'A','Mons', 'Jean-Baptiste van'),
('1631', 'A','Montagne', 'Jean François Camille'),
('1632', 'A','Nieuport', 'Charles François le Prudhomme de'),
('1633', 'A','Picot de la Peyrouse', 'Philippe Isidore'),
('1634', 'A','Robert', 'François'),
('1635', 'A','Roederer', 'Johann Georg'),
('1636', 'A','Schubert (Shubert)', 'Friedrich Theodor (Feodor Ivanovich)'),
('1637', 'A','Seba', 'Albert'),
('1638', 'A','Stratico', 'Simone'),
('1639', 'A','Triewald', 'Marten'),
('1640', 'A','Turner', 'Dawson'),
('1641', 'A','Cacciatore', 'Niccolo'),
('1642', 'A','Ozereckovskij', 'Nicolaï Iakovlevich'),
('1643', 'A','Hällström', 'Gustaf Gabriel'),
('1644', 'A','Rudberg', 'Fredrik'),
('1645', 'A','nan', 'nan')